#!/usr/bin/env python

# This should work in Python 2.7+ and Python 3.2+.

from __future__ import print_function

import argparse

import Miranda
import Config
import Action.Push
import Action.AddNode

#####
# Command line options.
parser = argparse.ArgumentParser()
parser.add_argument(
    'host',
    help = 'Host on which Miranda runs.'
)
parser.add_argument(
    'port',
    type = int,
    help = 'Port on which Miranda runs.'
)
parser.add_argument(
    '--push',
    dest = 'action',
    action = 'store_const',
    const = 'push',
    help = 'Push code to server.'
)
parser.add_argument(
    '--repo-type',
    dest = 'repo_type',
    default = 'auto',
    help = 'Application repository type (default is auto discovery).'
)
parser.add_argument(
    '--add-node',
    dest = 'node_info',
    help = 'Add a new Cortex node.  You should specify host:port of a new node '
        '(host should be the same as set in Miranda.Config)'
)
#####

#####
# Parse the command line options.
args = parser.parse_args()
#####

Config.init()
Miranda.init(args.host, args.port)

if args.action == 'push':
    Action.Push.perform(args.repo_type)
elif args.node_info is not None:
    Action.AddNode.perform(args.node_info)
else:
    print('You have to specify an action.')
