#!/usr/bin/env python

# This should work in Python 2.7+ and Python 3.2+.

from __future__ import print_function

import argparse

import Miranda
import Config
import Action.Push
import Action.AddNode
import Action.Instances
import Action.Info
import Action.NewApp

#####
# Command line options.
parser = argparse.ArgumentParser()
parser.add_argument(
    'host',
    help = 'Host on which Miranda runs.'
)
parser.add_argument(
    'port',
    type = int,
    help = 'Port on which Miranda runs.'
)
parser.add_argument(
    '--push',
    dest = 'action',
    action = 'store_const',
    const = 'push',
    help = 'Push code to server.'
)
parser.add_argument(
    '--repo-type',
    dest = 'repo_type',
    default = 'auto',
    help = 'Application repository type (default is auto discovery).'
)
parser.add_argument(
    '--instances',
    dest = 'instances',
    type = int,
    help = 'Set how many instances of this application Cortex should run.'
)
parser.add_argument(
    '--info',
    dest = 'action',
    action = 'store_const',
    const = 'info',
    help = 'Get current Cortex settings for this application.'
)
parser.add_argument(
    '--add-node',
    dest = 'node_info',
    help = 'Add a new Cortex node.  You should specify host:port of a new node '
        '(host should be the same as set in Miranda.Config).'
)
parser.add_argument(
    '--new-app',
    dest = 'action',
    action = 'store_const',
    const = 'new_app',
    help = 'Set up a new application.'
)
parser.add_argument(
    '--app-type',
    dest = 'app_type',
    default = 'auto',
    help = 'New application type (default is auto discovery).'
)
#####

#####
# Parse the command line options.
args = parser.parse_args()
#####

Config.init()
Miranda.init(args.host, args.port)

if args.action == 'push':
    Action.Push.perform(args.repo_type)
elif args.node_info is not None:
    Action.AddNode.perform(args.node_info)
elif args.instances is not None:
    Action.Instances.perform(args.instances)
elif args.action == 'info':
    Action.Info.perform()
elif args.action == 'new_app':
    Action.NewApp.perform(args.app_type)
else:
    print('You have to specify an action.')
